### ISSUE TITLE
Add MVVM pattern to the proyect

### ISSUE THREAD

**Issue by erickconcepcion** [erickconcepcion/MyManga#4]
The MVVM pattern help us on manage databinding to increase the performance.

**Comment by erickconcepcion** [comment]
i'll go implement MVVM Light

**Comment by YhorbyMatias** [comment]
why you pick up MVVm Light ?

**Comment by YhorbyMatias** [comment]
I recommend PRIMS  check those links that could be useful for you 
https://medium.com/tutorialsxl/xamarin-forms-with-prism-getting-started-part-1-14832d7cf5fa
 https://prismlibrary.github.io/docs/xamarin-forms/Getting-Started.html

**Comment by erickconcepcion** [comment]
Bicause i read that MVVMLight is the simplest, but getting deep into the Xamarin core MVVM manager is better cause you can use the same components of Light without installing nuget.
I meanning ViewModels, Dependency injection, Messengers etc.

**Comment by erickconcepcion** [comment]
> I recommend PRIMS check those links that could be useful for you
> https://medium.com/tutorialsxl/xamarin-forms-with-prism-getting-started-part-1-14832d7cf5fa
> https://prismlibrary.github.io/docs/xamarin-forms/Getting-Started.html

i'll do

**Comment by erickconcepcion** [comment]
i'll use this [doc]( https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/) to applay MVVM with the argument of learn the basis to have a choose criteria on MVVM Framework.
